# Logistic Regression for Binary Classification.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('insurance_data_l8.csv')

In [3]:
df.head()

   age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [18]:
# Doing x = df.age will create a series (a,), won't be able to train.

x = df[['age']]
x

    age
0    22
1    25
2    47
3    52
4    46
5    56
6    55
7    60
8    62
9    61
10   18
11   28
12   27
13   29
14   49
15   55
16   25
17   58
18   19
19   18
20   21
21   26
22   40
23   45
24   50
25   54
26   23

In [19]:
y = df.bought_insurance

In [20]:
# spliting the data for training and testing. 
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [22]:
# getting the model and fitting it.
from sklearn.linear_model import LogisticRegression

In [23]:
model = LogisticRegression()
X_train.shape

(21, 1)

In [24]:
model.fit(X_train, y_train)

LogisticRegression()

In [27]:
model.score(X_test, y_test)

1.0

In [29]:
model.predict([[6]])

C:\Users\piyus\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [30]:
model.predict([[60]])

C:\Users\piyus\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])